/* Assembly language implementation of hexdump functions */

	.section .rodata

	/* TODO: add read-only data such as strings here */

	.section .text

	/* TODO: add functions here */
		.globl hex_read
		.globl hex_write_string
		.globl hex_format_offset
		.globl hex_format_byte_as_hex
		.globl hex_to_printable
		

	hex_read:
		/* TODO: implement function */
		ret

	hex_write_string:
		/* TODO: implement function */
		ret

	hex_format_offset:
		/* TODO: implement function */
		ret

	hex_format_byte_as_hex:
		/* TODO: implement function */
		ret

	hex_to_printable:
		/* TODO: implement function */
		ret
		
/* vim:ft=gas:
 */
